#ifndef __S2_IPORT_V04_2_H__
#define __S2_IPORT_V04_2_H__




/*
* Constructor and Destructor
*/

/*
* DIGITAL_INPUT
*/
#define __S2_iPort_v04_2_MUSIC_MENU_DIG_INPUT 0
#define __S2_iPort_v04_2_VIDEO_MENU_DIG_INPUT 1
#define __S2_iPort_v04_2_MENU_DIG_INPUT 2
#define __S2_iPort_v04_2_ENTER_DIG_INPUT 3
#define __S2_iPort_v04_2_PLAY_PAUSE_DIG_INPUT 4
#define __S2_iPort_v04_2_UP_DIG_INPUT 5
#define __S2_iPort_v04_2_DOWN_DIG_INPUT 6
#define __S2_iPort_v04_2_FAST_UP_DIG_INPUT 7
#define __S2_iPort_v04_2_FAST_DOWN_DIG_INPUT 8
#define __S2_iPort_v04_2_REPEAT_DIG_INPUT 9
#define __S2_iPort_v04_2_REPEAT_ONE_DIG_INPUT 10
#define __S2_iPort_v04_2_REPEAT_ALL_DIG_INPUT 11
#define __S2_iPort_v04_2_REPEAT_OFF_DIG_INPUT 12
#define __S2_iPort_v04_2_SHUFFLE_DIG_INPUT 13
#define __S2_iPort_v04_2_SHUFFLE_SONGS_DIG_INPUT 14
#define __S2_iPort_v04_2_SHUFFLE_ALBUMS_DIG_INPUT 15
#define __S2_iPort_v04_2_SHUFFLE_OFF_DIG_INPUT 16
#define __S2_iPort_v04_2_PLAY_CURR_SEL_DIG_INPUT 17
#define __S2_iPort_v04_2_PLAY_DIG_INPUT 18
#define __S2_iPort_v04_2_PAUSE_DIG_INPUT 19
#define __S2_iPort_v04_2_STOP_DIG_INPUT 20
#define __S2_iPort_v04_2_NEXT_TRACK_DIG_INPUT 21
#define __S2_iPort_v04_2_PREV_TRACK_DIG_INPUT 22
#define __S2_iPort_v04_2_FFWD_DIG_INPUT 23
#define __S2_iPort_v04_2_REW_DIG_INPUT 24
#define __S2_iPort_v04_2_SLIDER_PRESS_DIG_INPUT 25
#define __S2_iPort_v04_2_DISABLE_NOTIF_DIG_INPUT 26
#define __S2_iPort_v04_2_PLAY_ON_DOCK_DIG_INPUT 27
#define __S2_iPort_v04_2_LINE1_PRESS_DIG_INPUT 28
#define __S2_iPort_v04_2_LINE2_PRESS_DIG_INPUT 29
#define __S2_iPort_v04_2_LINE3_PRESS_DIG_INPUT 30
#define __S2_iPort_v04_2_LINE4_PRESS_DIG_INPUT 31
#define __S2_iPort_v04_2_LINE5_PRESS_DIG_INPUT 32
#define __S2_iPort_v04_2_LINE6_PRESS_DIG_INPUT 33
#define __S2_iPort_v04_2_LINE7_PRESS_DIG_INPUT 34
#define __S2_iPort_v04_2_LINE8_PRESS_DIG_INPUT 35
#define __S2_iPort_v04_2_LINE9_PRESS_DIG_INPUT 36
#define __S2_iPort_v04_2_LINE10_PRESS_DIG_INPUT 37
#define __S2_iPort_v04_2_LINE11_PRESS_DIG_INPUT 38
#define __S2_iPort_v04_2_LINE12_PRESS_DIG_INPUT 39
#define __S2_iPort_v04_2_LINE13_PRESS_DIG_INPUT 40
#define __S2_iPort_v04_2_LINE14_PRESS_DIG_INPUT 41
#define __S2_iPort_v04_2_LINE15_PRESS_DIG_INPUT 42
#define __S2_iPort_v04_2_LINE16_PRESS_DIG_INPUT 43
#define __S2_iPort_v04_2_LINE17_PRESS_DIG_INPUT 44
#define __S2_iPort_v04_2_LINE18_PRESS_DIG_INPUT 45
#define __S2_iPort_v04_2_LINE19_PRESS_DIG_INPUT 46
#define __S2_iPort_v04_2_LINE20_PRESS_DIG_INPUT 47
#define __S2_iPort_v04_2_LINE21_PRESS_DIG_INPUT 48
#define __S2_iPort_v04_2_LINE22_PRESS_DIG_INPUT 49
#define __S2_iPort_v04_2_LINE23_PRESS_DIG_INPUT 50
#define __S2_iPort_v04_2_LINE24_PRESS_DIG_INPUT 51
#define __S2_iPort_v04_2_LINE25_PRESS_DIG_INPUT 52
#define __S2_iPort_v04_2_LINE26_PRESS_DIG_INPUT 53
#define __S2_iPort_v04_2_LINE27_PRESS_DIG_INPUT 54
#define __S2_iPort_v04_2_LINE28_PRESS_DIG_INPUT 55
#define __S2_iPort_v04_2_LINE29_PRESS_DIG_INPUT 56
#define __S2_iPort_v04_2_LINE30_PRESS_DIG_INPUT 57
#define __S2_iPort_v04_2_LINE31_PRESS_DIG_INPUT 58
#define __S2_iPort_v04_2_LINE32_PRESS_DIG_INPUT 59
#define __S2_iPort_v04_2_ENTER_REM_UI_DIG_INPUT 60
#define __S2_iPort_v04_2_EXIT_REM_UI_DIG_INPUT 61
#define __S2_iPort_v04_2_REQUEST_FIRM_VER_DIG_INPUT 62


/*
* ANALOG_INPUT
*/
#define __S2_iPort_v04_2_SLIDER_IN_ANALOG_INPUT 0
#define __S2_iPort_v04_2_FAST_NUM_OF_REC_ANALOG_INPUT 1
#define __S2_iPort_v04_2_CHAR_IN_REC_10TO50_ANALOG_INPUT 2
#define __S2_iPort_v04_2_NUM_OF_LINES_2TO32_ANALOG_INPUT 3


#define __S2_iPort_v04_2_DATA_IN$_BUFFER_INPUT 4
#define __S2_iPort_v04_2_DATA_IN$_BUFFER_MAX_LEN 1000
CREATE_STRING_STRUCT( S2_iPort_v04_2, __DATA_IN$, __S2_iPort_v04_2_DATA_IN$_BUFFER_MAX_LEN );


/*
* DIGITAL_OUTPUT
*/
#define __S2_iPort_v04_2_MUSIC_MENU_FB_DIG_OUTPUT 0
#define __S2_iPort_v04_2_VIDEO_MENU_FB_DIG_OUTPUT 1
#define __S2_iPort_v04_2_OUT_LINE1_FB_DIG_OUTPUT 2
#define __S2_iPort_v04_2_OUT_LINE2_FB_DIG_OUTPUT 3
#define __S2_iPort_v04_2_OUT_LINE3_FB_DIG_OUTPUT 4
#define __S2_iPort_v04_2_OUT_LINE4_FB_DIG_OUTPUT 5
#define __S2_iPort_v04_2_OUT_LINE5_FB_DIG_OUTPUT 6
#define __S2_iPort_v04_2_OUT_LINE6_FB_DIG_OUTPUT 7
#define __S2_iPort_v04_2_OUT_LINE7_FB_DIG_OUTPUT 8
#define __S2_iPort_v04_2_OUT_LINE8_FB_DIG_OUTPUT 9
#define __S2_iPort_v04_2_OUT_LINE9_FB_DIG_OUTPUT 10
#define __S2_iPort_v04_2_OUT_LINE10_FB_DIG_OUTPUT 11
#define __S2_iPort_v04_2_OUT_LINE11_FB_DIG_OUTPUT 12
#define __S2_iPort_v04_2_OUT_LINE12_FB_DIG_OUTPUT 13
#define __S2_iPort_v04_2_OUT_LINE13_FB_DIG_OUTPUT 14
#define __S2_iPort_v04_2_OUT_LINE14_FB_DIG_OUTPUT 15
#define __S2_iPort_v04_2_OUT_LINE15_FB_DIG_OUTPUT 16
#define __S2_iPort_v04_2_OUT_LINE16_FB_DIG_OUTPUT 17
#define __S2_iPort_v04_2_OUT_LINE17_FB_DIG_OUTPUT 18
#define __S2_iPort_v04_2_OUT_LINE18_FB_DIG_OUTPUT 19
#define __S2_iPort_v04_2_OUT_LINE19_FB_DIG_OUTPUT 20
#define __S2_iPort_v04_2_OUT_LINE20_FB_DIG_OUTPUT 21
#define __S2_iPort_v04_2_OUT_LINE21_FB_DIG_OUTPUT 22
#define __S2_iPort_v04_2_OUT_LINE22_FB_DIG_OUTPUT 23
#define __S2_iPort_v04_2_OUT_LINE23_FB_DIG_OUTPUT 24
#define __S2_iPort_v04_2_OUT_LINE24_FB_DIG_OUTPUT 25
#define __S2_iPort_v04_2_OUT_LINE25_FB_DIG_OUTPUT 26
#define __S2_iPort_v04_2_OUT_LINE26_FB_DIG_OUTPUT 27
#define __S2_iPort_v04_2_OUT_LINE27_FB_DIG_OUTPUT 28
#define __S2_iPort_v04_2_OUT_LINE28_FB_DIG_OUTPUT 29
#define __S2_iPort_v04_2_OUT_LINE29_FB_DIG_OUTPUT 30
#define __S2_iPort_v04_2_OUT_LINE30_FB_DIG_OUTPUT 31
#define __S2_iPort_v04_2_OUT_LINE31_FB_DIG_OUTPUT 32
#define __S2_iPort_v04_2_OUT_LINE32_FB_DIG_OUTPUT 33
#define __S2_iPort_v04_2_PLAY_FB_DIG_OUTPUT 34
#define __S2_iPort_v04_2_PAUSE_FB_DIG_OUTPUT 35
#define __S2_iPort_v04_2_STOP_FB_DIG_OUTPUT 36
#define __S2_iPort_v04_2_FFWD_FB_DIG_OUTPUT 37
#define __S2_iPort_v04_2_REW_FB_DIG_OUTPUT 38
#define __S2_iPort_v04_2_REPEAT_ONE_FB_DIG_OUTPUT 39
#define __S2_iPort_v04_2_REPEAT_ALL_FB_DIG_OUTPUT 40
#define __S2_iPort_v04_2_REPEAT_OFF_FB_DIG_OUTPUT 41
#define __S2_iPort_v04_2_SHUFFLE_SONGS_FB_DIG_OUTPUT 42
#define __S2_iPort_v04_2_SHUFFLE_ALBUMS_FB_DIG_OUTPUT 43
#define __S2_iPort_v04_2_SHUFFLE_OFF_FB_DIG_OUTPUT 44
#define __S2_iPort_v04_2_PLAYER_FB_DIG_OUTPUT 45
#define __S2_iPort_v04_2_BROWSE_FB_DIG_OUTPUT 46
#define __S2_iPort_v04_2_IPOD_IS_IN_DIG_OUTPUT 47
#define __S2_iPort_v04_2_IPOD_IS_OUT_DIG_OUTPUT 48
#define __S2_iPort_v04_2_REMOTE_UI_MODE_DIG_OUTPUT 49
#define __S2_iPort_v04_2_LOCAL_UI_MODE_DIG_OUTPUT 50


/*
* ANALOG_OUTPUT
*/
#define __S2_iPort_v04_2_PL_SONG_INDEX_ANALOG_OUTPUT 0
#define __S2_iPort_v04_2_NUM_PL_SONG_ANALOG_OUTPUT 1
#define __S2_iPort_v04_2_TOTAL_MIN_ANALOG_OUTPUT 2
#define __S2_iPort_v04_2_TOTAL_SEC_ANALOG_OUTPUT 3
#define __S2_iPort_v04_2_TOTAL_IN_SEC_ANALOG_OUTPUT 4
#define __S2_iPort_v04_2_ELAPS_MIN_ANALOG_OUTPUT 5
#define __S2_iPort_v04_2_ELAPS_SEC_ANALOG_OUTPUT 6
#define __S2_iPort_v04_2_ELAPS_IN_SEC_ANALOG_OUTPUT 7
#define __S2_iPort_v04_2_REMAIN_MIN_ANALOG_OUTPUT 8
#define __S2_iPort_v04_2_REMAIN_SEC_ANALOG_OUTPUT 9
#define __S2_iPort_v04_2_REMAIN_IN_SEC_ANALOG_OUTPUT 10
#define __S2_iPort_v04_2_TIME_BAR_ANALOG_OUTPUT 11
#define __S2_iPort_v04_2_SLIDER_FB_ANALOG_OUTPUT 12

#define __S2_iPort_v04_2_PAGE_TITLE$_STRING_OUTPUT 13
#define __S2_iPort_v04_2_OUT_LINE1$_STRING_OUTPUT 14
#define __S2_iPort_v04_2_OUT_LINE2$_STRING_OUTPUT 15
#define __S2_iPort_v04_2_OUT_LINE3$_STRING_OUTPUT 16
#define __S2_iPort_v04_2_OUT_LINE4$_STRING_OUTPUT 17
#define __S2_iPort_v04_2_OUT_LINE5$_STRING_OUTPUT 18
#define __S2_iPort_v04_2_OUT_LINE6$_STRING_OUTPUT 19
#define __S2_iPort_v04_2_OUT_LINE7$_STRING_OUTPUT 20
#define __S2_iPort_v04_2_OUT_LINE8$_STRING_OUTPUT 21
#define __S2_iPort_v04_2_OUT_LINE9$_STRING_OUTPUT 22
#define __S2_iPort_v04_2_OUT_LINE10$_STRING_OUTPUT 23
#define __S2_iPort_v04_2_OUT_LINE11$_STRING_OUTPUT 24
#define __S2_iPort_v04_2_OUT_LINE12$_STRING_OUTPUT 25
#define __S2_iPort_v04_2_OUT_LINE13$_STRING_OUTPUT 26
#define __S2_iPort_v04_2_OUT_LINE14$_STRING_OUTPUT 27
#define __S2_iPort_v04_2_OUT_LINE15$_STRING_OUTPUT 28
#define __S2_iPort_v04_2_OUT_LINE16$_STRING_OUTPUT 29
#define __S2_iPort_v04_2_OUT_LINE17$_STRING_OUTPUT 30
#define __S2_iPort_v04_2_OUT_LINE18$_STRING_OUTPUT 31
#define __S2_iPort_v04_2_OUT_LINE19$_STRING_OUTPUT 32
#define __S2_iPort_v04_2_OUT_LINE20$_STRING_OUTPUT 33
#define __S2_iPort_v04_2_OUT_LINE21$_STRING_OUTPUT 34
#define __S2_iPort_v04_2_OUT_LINE22$_STRING_OUTPUT 35
#define __S2_iPort_v04_2_OUT_LINE23$_STRING_OUTPUT 36
#define __S2_iPort_v04_2_OUT_LINE24$_STRING_OUTPUT 37
#define __S2_iPort_v04_2_OUT_LINE25$_STRING_OUTPUT 38
#define __S2_iPort_v04_2_OUT_LINE26$_STRING_OUTPUT 39
#define __S2_iPort_v04_2_OUT_LINE27$_STRING_OUTPUT 40
#define __S2_iPort_v04_2_OUT_LINE28$_STRING_OUTPUT 41
#define __S2_iPort_v04_2_OUT_LINE29$_STRING_OUTPUT 42
#define __S2_iPort_v04_2_OUT_LINE30$_STRING_OUTPUT 43
#define __S2_iPort_v04_2_OUT_LINE31$_STRING_OUTPUT 44
#define __S2_iPort_v04_2_OUT_LINE32$_STRING_OUTPUT 45
#define __S2_iPort_v04_2_PLAYING_ALBUM$_STRING_OUTPUT 46
#define __S2_iPort_v04_2_PLAYING_TITLE$_STRING_OUTPUT 47
#define __S2_iPort_v04_2_PLAYING_ARTIST$_STRING_OUTPUT 48
#define __S2_iPort_v04_2_IPOD_NAME$_STRING_OUTPUT 49
#define __S2_iPort_v04_2_FIRMWARE_VER$_STRING_OUTPUT 50
#define __S2_iPort_v04_2_OUT_TO_IPORT$_STRING_OUTPUT 51


/*
* Direct Socket Variables
*/




/*
* INTEGER_PARAMETER
*/
/*
* SIGNED_INTEGER_PARAMETER
*/
/*
* LONG_INTEGER_PARAMETER
*/
/*
* SIGNED_LONG_INTEGER_PARAMETER
*/
/*
* INTEGER_PARAMETER
*/
/*
* SIGNED_INTEGER_PARAMETER
*/
/*
* LONG_INTEGER_PARAMETER
*/
/*
* SIGNED_LONG_INTEGER_PARAMETER
*/
/*
* STRING_PARAMETER
*/


/*
* INTEGER
*/


/*
* LONG_INTEGER
*/


/*
* SIGNED_INTEGER
*/


/*
* SIGNED_LONG_INTEGER
*/


/*
* STRING
*/
#define __S2_iPort_v04_2_TEMP$_STRING_MAX_LEN 200
CREATE_STRING_STRUCT( S2_iPort_v04_2, __TEMP$, __S2_iPort_v04_2_TEMP$_STRING_MAX_LEN );
#define __S2_iPort_v04_2_PLAYER_PAGE_TITLE$_STRING_MAX_LEN 200
CREATE_STRING_STRUCT( S2_iPort_v04_2, __PLAYER_PAGE_TITLE$, __S2_iPort_v04_2_PLAYER_PAGE_TITLE$_STRING_MAX_LEN );
#define __S2_iPort_v04_2_PAGE_TITLE_BUF$_STRING_MAX_LEN 200
CREATE_STRING_STRUCT( S2_iPort_v04_2, __PAGE_TITLE_BUF$, __S2_iPort_v04_2_PAGE_TITLE_BUF$_STRING_MAX_LEN );
#define __S2_iPort_v04_2_TITLE_PLAYLIST$_STRING_MAX_LEN 200
CREATE_STRING_STRUCT( S2_iPort_v04_2, __TITLE_PLAYLIST$, __S2_iPort_v04_2_TITLE_PLAYLIST$_STRING_MAX_LEN );
#define __S2_iPort_v04_2_TITLE_ARTIST$_STRING_MAX_LEN 200
CREATE_STRING_STRUCT( S2_iPort_v04_2, __TITLE_ARTIST$, __S2_iPort_v04_2_TITLE_ARTIST$_STRING_MAX_LEN );
#define __S2_iPort_v04_2_TITLE_ALBUM$_STRING_MAX_LEN 200
CREATE_STRING_STRUCT( S2_iPort_v04_2, __TITLE_ALBUM$, __S2_iPort_v04_2_TITLE_ALBUM$_STRING_MAX_LEN );
#define __S2_iPort_v04_2_TITLE_GENRE$_STRING_MAX_LEN 200
CREATE_STRING_STRUCT( S2_iPort_v04_2, __TITLE_GENRE$, __S2_iPort_v04_2_TITLE_GENRE$_STRING_MAX_LEN );
#define __S2_iPort_v04_2_TITLE_COMPOSER$_STRING_MAX_LEN 200
CREATE_STRING_STRUCT( S2_iPort_v04_2, __TITLE_COMPOSER$, __S2_iPort_v04_2_TITLE_COMPOSER$_STRING_MAX_LEN );
#define __S2_iPort_v04_2_TITLE_PODCAST$_STRING_MAX_LEN 200
CREATE_STRING_STRUCT( S2_iPort_v04_2, __TITLE_PODCAST$, __S2_iPort_v04_2_TITLE_PODCAST$_STRING_MAX_LEN );
#define __S2_iPort_v04_2_TITLE_AUDIOBOOK$_STRING_MAX_LEN 200
CREATE_STRING_STRUCT( S2_iPort_v04_2, __TITLE_AUDIOBOOK$, __S2_iPort_v04_2_TITLE_AUDIOBOOK$_STRING_MAX_LEN );
#define __S2_iPort_v04_2_OUT_LINE1_BUF$_STRING_MAX_LEN 200
CREATE_STRING_STRUCT( S2_iPort_v04_2, __OUT_LINE1_BUF$, __S2_iPort_v04_2_OUT_LINE1_BUF$_STRING_MAX_LEN );
#define __S2_iPort_v04_2_OUT_LINE2_BUF$_STRING_MAX_LEN 200
CREATE_STRING_STRUCT( S2_iPort_v04_2, __OUT_LINE2_BUF$, __S2_iPort_v04_2_OUT_LINE2_BUF$_STRING_MAX_LEN );
#define __S2_iPort_v04_2_OUT_LINE3_BUF$_STRING_MAX_LEN 200
CREATE_STRING_STRUCT( S2_iPort_v04_2, __OUT_LINE3_BUF$, __S2_iPort_v04_2_OUT_LINE3_BUF$_STRING_MAX_LEN );
#define __S2_iPort_v04_2_OUT_LINE4_BUF$_STRING_MAX_LEN 200
CREATE_STRING_STRUCT( S2_iPort_v04_2, __OUT_LINE4_BUF$, __S2_iPort_v04_2_OUT_LINE4_BUF$_STRING_MAX_LEN );
#define __S2_iPort_v04_2_OUT_LINE5_BUF$_STRING_MAX_LEN 200
CREATE_STRING_STRUCT( S2_iPort_v04_2, __OUT_LINE5_BUF$, __S2_iPort_v04_2_OUT_LINE5_BUF$_STRING_MAX_LEN );
#define __S2_iPort_v04_2_OUT_LINE6_BUF$_STRING_MAX_LEN 200
CREATE_STRING_STRUCT( S2_iPort_v04_2, __OUT_LINE6_BUF$, __S2_iPort_v04_2_OUT_LINE6_BUF$_STRING_MAX_LEN );
#define __S2_iPort_v04_2_OUT_LINE7_BUF$_STRING_MAX_LEN 200
CREATE_STRING_STRUCT( S2_iPort_v04_2, __OUT_LINE7_BUF$, __S2_iPort_v04_2_OUT_LINE7_BUF$_STRING_MAX_LEN );
#define __S2_iPort_v04_2_OUT_LINE8_BUF$_STRING_MAX_LEN 200
CREATE_STRING_STRUCT( S2_iPort_v04_2, __OUT_LINE8_BUF$, __S2_iPort_v04_2_OUT_LINE8_BUF$_STRING_MAX_LEN );
#define __S2_iPort_v04_2_OUT_LINE9_BUF$_STRING_MAX_LEN 200
CREATE_STRING_STRUCT( S2_iPort_v04_2, __OUT_LINE9_BUF$, __S2_iPort_v04_2_OUT_LINE9_BUF$_STRING_MAX_LEN );
#define __S2_iPort_v04_2_OUT_LINE10_BUF$_STRING_MAX_LEN 200
CREATE_STRING_STRUCT( S2_iPort_v04_2, __OUT_LINE10_BUF$, __S2_iPort_v04_2_OUT_LINE10_BUF$_STRING_MAX_LEN );
#define __S2_iPort_v04_2_OUT_LINE11_BUF$_STRING_MAX_LEN 200
CREATE_STRING_STRUCT( S2_iPort_v04_2, __OUT_LINE11_BUF$, __S2_iPort_v04_2_OUT_LINE11_BUF$_STRING_MAX_LEN );
#define __S2_iPort_v04_2_OUT_LINE12_BUF$_STRING_MAX_LEN 200
CREATE_STRING_STRUCT( S2_iPort_v04_2, __OUT_LINE12_BUF$, __S2_iPort_v04_2_OUT_LINE12_BUF$_STRING_MAX_LEN );
#define __S2_iPort_v04_2_OUT_LINE13_BUF$_STRING_MAX_LEN 200
CREATE_STRING_STRUCT( S2_iPort_v04_2, __OUT_LINE13_BUF$, __S2_iPort_v04_2_OUT_LINE13_BUF$_STRING_MAX_LEN );
#define __S2_iPort_v04_2_OUT_LINE14_BUF$_STRING_MAX_LEN 200
CREATE_STRING_STRUCT( S2_iPort_v04_2, __OUT_LINE14_BUF$, __S2_iPort_v04_2_OUT_LINE14_BUF$_STRING_MAX_LEN );
#define __S2_iPort_v04_2_OUT_LINE15_BUF$_STRING_MAX_LEN 200
CREATE_STRING_STRUCT( S2_iPort_v04_2, __OUT_LINE15_BUF$, __S2_iPort_v04_2_OUT_LINE15_BUF$_STRING_MAX_LEN );
#define __S2_iPort_v04_2_OUT_LINE16_BUF$_STRING_MAX_LEN 200
CREATE_STRING_STRUCT( S2_iPort_v04_2, __OUT_LINE16_BUF$, __S2_iPort_v04_2_OUT_LINE16_BUF$_STRING_MAX_LEN );
#define __S2_iPort_v04_2_OUT_LINE17_BUF$_STRING_MAX_LEN 200
CREATE_STRING_STRUCT( S2_iPort_v04_2, __OUT_LINE17_BUF$, __S2_iPort_v04_2_OUT_LINE17_BUF$_STRING_MAX_LEN );
#define __S2_iPort_v04_2_OUT_LINE18_BUF$_STRING_MAX_LEN 200
CREATE_STRING_STRUCT( S2_iPort_v04_2, __OUT_LINE18_BUF$, __S2_iPort_v04_2_OUT_LINE18_BUF$_STRING_MAX_LEN );
#define __S2_iPort_v04_2_OUT_LINE19_BUF$_STRING_MAX_LEN 200
CREATE_STRING_STRUCT( S2_iPort_v04_2, __OUT_LINE19_BUF$, __S2_iPort_v04_2_OUT_LINE19_BUF$_STRING_MAX_LEN );
#define __S2_iPort_v04_2_OUT_LINE20_BUF$_STRING_MAX_LEN 200
CREATE_STRING_STRUCT( S2_iPort_v04_2, __OUT_LINE20_BUF$, __S2_iPort_v04_2_OUT_LINE20_BUF$_STRING_MAX_LEN );
#define __S2_iPort_v04_2_OUT_LINE21_BUF$_STRING_MAX_LEN 200
CREATE_STRING_STRUCT( S2_iPort_v04_2, __OUT_LINE21_BUF$, __S2_iPort_v04_2_OUT_LINE21_BUF$_STRING_MAX_LEN );
#define __S2_iPort_v04_2_OUT_LINE22_BUF$_STRING_MAX_LEN 200
CREATE_STRING_STRUCT( S2_iPort_v04_2, __OUT_LINE22_BUF$, __S2_iPort_v04_2_OUT_LINE22_BUF$_STRING_MAX_LEN );
#define __S2_iPort_v04_2_OUT_LINE23_BUF$_STRING_MAX_LEN 200
CREATE_STRING_STRUCT( S2_iPort_v04_2, __OUT_LINE23_BUF$, __S2_iPort_v04_2_OUT_LINE23_BUF$_STRING_MAX_LEN );
#define __S2_iPort_v04_2_OUT_LINE24_BUF$_STRING_MAX_LEN 200
CREATE_STRING_STRUCT( S2_iPort_v04_2, __OUT_LINE24_BUF$, __S2_iPort_v04_2_OUT_LINE24_BUF$_STRING_MAX_LEN );
#define __S2_iPort_v04_2_OUT_LINE25_BUF$_STRING_MAX_LEN 200
CREATE_STRING_STRUCT( S2_iPort_v04_2, __OUT_LINE25_BUF$, __S2_iPort_v04_2_OUT_LINE25_BUF$_STRING_MAX_LEN );
#define __S2_iPort_v04_2_OUT_LINE26_BUF$_STRING_MAX_LEN 200
CREATE_STRING_STRUCT( S2_iPort_v04_2, __OUT_LINE26_BUF$, __S2_iPort_v04_2_OUT_LINE26_BUF$_STRING_MAX_LEN );
#define __S2_iPort_v04_2_OUT_LINE27_BUF$_STRING_MAX_LEN 200
CREATE_STRING_STRUCT( S2_iPort_v04_2, __OUT_LINE27_BUF$, __S2_iPort_v04_2_OUT_LINE27_BUF$_STRING_MAX_LEN );
#define __S2_iPort_v04_2_OUT_LINE28_BUF$_STRING_MAX_LEN 200
CREATE_STRING_STRUCT( S2_iPort_v04_2, __OUT_LINE28_BUF$, __S2_iPort_v04_2_OUT_LINE28_BUF$_STRING_MAX_LEN );
#define __S2_iPort_v04_2_OUT_LINE29_BUF$_STRING_MAX_LEN 200
CREATE_STRING_STRUCT( S2_iPort_v04_2, __OUT_LINE29_BUF$, __S2_iPort_v04_2_OUT_LINE29_BUF$_STRING_MAX_LEN );
#define __S2_iPort_v04_2_OUT_LINE30_BUF$_STRING_MAX_LEN 200
CREATE_STRING_STRUCT( S2_iPort_v04_2, __OUT_LINE30_BUF$, __S2_iPort_v04_2_OUT_LINE30_BUF$_STRING_MAX_LEN );
#define __S2_iPort_v04_2_OUT_LINE31_BUF$_STRING_MAX_LEN 200
CREATE_STRING_STRUCT( S2_iPort_v04_2, __OUT_LINE31_BUF$, __S2_iPort_v04_2_OUT_LINE31_BUF$_STRING_MAX_LEN );
#define __S2_iPort_v04_2_OUT_LINE32_BUF$_STRING_MAX_LEN 200
CREATE_STRING_STRUCT( S2_iPort_v04_2, __OUT_LINE32_BUF$, __S2_iPort_v04_2_OUT_LINE32_BUF$_STRING_MAX_LEN );
#define __S2_iPort_v04_2_DATA_TO_PROCESS$_STRING_MAX_LEN 255
CREATE_STRING_STRUCT( S2_iPort_v04_2, __DATA_TO_PROCESS$, __S2_iPort_v04_2_DATA_TO_PROCESS$_STRING_MAX_LEN );
#define __S2_iPort_v04_2_TEMP_LINE_OUT$_STRING_MAX_LEN 255
CREATE_STRING_STRUCT( S2_iPort_v04_2, __TEMP_LINE_OUT$, __S2_iPort_v04_2_TEMP_LINE_OUT$_STRING_MAX_LEN );
#define __S2_iPort_v04_2_TEMP_FIRMWARE_VER$_STRING_MAX_LEN 20
CREATE_STRING_STRUCT( S2_iPort_v04_2, __TEMP_FIRMWARE_VER$, __S2_iPort_v04_2_TEMP_FIRMWARE_VER$_STRING_MAX_LEN );
#define __S2_iPort_v04_2_DATA_TO_PROCESS_TEMP$_STRING_MAX_LEN 255
CREATE_STRING_STRUCT( S2_iPort_v04_2, __DATA_TO_PROCESS_TEMP$, __S2_iPort_v04_2_DATA_TO_PROCESS_TEMP$_STRING_MAX_LEN );

/*
* STRUCTURE
*/

START_GLOBAL_VAR_STRUCT( S2_iPort_v04_2 )
{
   void* InstancePtr;
   struct GenericOutputString_s sGenericOutStr;
   unsigned short LastModifiedArrayIndex;

   unsigned short __CHAR_1;
   unsigned short __CHAR_2;
   unsigned short __CHAR_3;
   unsigned short __CHAR_4;
   unsigned short __CHAR_INDEX;
   unsigned short __PACKET_LENGHT;
   unsigned short __CURR_PATH;
   unsigned short __CURR_CATEGORY;
   unsigned short __NUM_OF_PLAYLISTS;
   unsigned short __NUM_OF_ARTISTS;
   unsigned short __NUM_OF_ALBUMS;
   unsigned short __NUM_OF_GENRES;
   unsigned short __NUM_OF_SONGS;
   unsigned short __NUM_OF_COMPOSERS;
   unsigned short __NUM_OF_PODCASTS;
   unsigned short __NUM_OF_AUDIOBOOKS;
   unsigned short __SONG_POSITION_B4;
   unsigned short __SONG_POSITION_B3;
   unsigned short __SONG_POSITION_B2;
   unsigned short __SONG_POSITION_B1;
   unsigned short __SONG_LENGHT_B4;
   unsigned short __SONG_LENGHT_B3;
   unsigned short __SONG_LENGHT_B2;
   unsigned short __SONG_LENGHT_B1;
   unsigned short __ANALIZE_IN_PROGRES;
   unsigned short __REC_CAR_IND_FLAG;
   unsigned short __NOTIF_ON_FLAG;
   unsigned short __FFWD_FROM_NEXT_FLAG;
   unsigned short __REW_FROM_PREV_FLAG;
   unsigned short __RXOK;
   unsigned short __UPDATE_PLAYER_FLAG;
   unsigned short __INDEX_CHANGE_FLAG;
   unsigned short __MENU_STATE;
   unsigned short __CHAR_IN_REC;
   unsigned short __NUM_OF_LINES;
   unsigned short __RETR_FLAG;
   unsigned short __DIS_SEND_RETR_REC_FLAG;
   unsigned short __REC_CHAR1;
   unsigned short __REC_CHAR2;
   unsigned short __REC_CHAR3;
   unsigned short __REC_CHAR4;
   unsigned short __REC_CHAR5;
   unsigned short __REC_CHAR6;
   unsigned short __REC_CHAR7;
   unsigned short __REC_CHAR8;
   unsigned short __REC_CHAR9;
   unsigned short __REC_CHAR_NEXT;
   unsigned short __REC_CHAR_INDEX;
   unsigned short __INDEX_FROM_REC_B1;
   unsigned short __INDEX_FROM_REC_B2;
   unsigned short __INDEX_FROM_REC_B3;
   unsigned short __INDEX_FROM_REC_B4;
   unsigned short __REC_LENGHT;
   unsigned short __PL_SONG_INDEX_B4;
   unsigned short __PL_SONG_INDEX_B3;
   unsigned short __PL_SONG_INDEX_B2;
   unsigned short __PL_SONG_INDEX_B1;
   unsigned short __NUM_PL_SONG_B4;
   unsigned short __NUM_PL_SONG_B3;
   unsigned short __NUM_PL_SONG_B2;
   unsigned short __NUM_PL_SONG_B1;
   unsigned short __PLAYER_STATUS;
   unsigned short __PLAYER_STATE_CODE;
   unsigned short __NUM_CAT_REC;
   unsigned short __NUM_CAT_REC_B1;
   unsigned short __NUM_CAT_REC_B2;
   unsigned short __NUM_CAT_REC_B3;
   unsigned short __NUM_CAT_REC_B4;
   unsigned short __REPEAT_CODE;
   unsigned short __SHUFFLE_CODE;
   unsigned short __ACK_CHAR;
   unsigned short __NEXT_CHAR_0;
   unsigned short __NEXT_CHAR_1;
   unsigned short __NEXT_CHAR_2;
   unsigned short __NEXT_CHAR_3;
   unsigned short __NEW_CHAR_0;
   unsigned short __NEW_CHAR_1;
   unsigned short __NEW_CHAR_2;
   unsigned short __STRING_BEGAN_FLAG;
   unsigned long __MAIN_INDEX;
   unsigned long __PLAYLIST_INDEX;
   unsigned long __ARTIST_INDEX;
   unsigned long __ALBUM_INDEX;
   unsigned long __SONG_INDEX;
   unsigned long __GENRE_INDEX;
   unsigned long __COMPOSER_INDEX;
   unsigned long __PODCAST_INDEX;
   unsigned long __AUDIOBOOK_INDEX;
   unsigned long __CURR_INDEX;
   unsigned long __PREV_CURR_INDEX;
   unsigned long __CURR_INDEX_DISP;
   unsigned long __PREV_INDEX_DISP;
   unsigned long __DISP_INDEX;
   unsigned long __CURR_IND_LOW_LIM;
   unsigned long __CURR_IND_UP_LIM;
   unsigned long __ELAPS_TIME_MS;
   unsigned long __TOTAL_TIME_MS;
   unsigned long __REMAIN_TIME_MS;
   unsigned long __FAST_N_O_R;
   unsigned long __INDEX_FROM_REC;
   DECLARE_STRING_STRUCT( S2_iPort_v04_2, __TEMP$ );
   DECLARE_STRING_STRUCT( S2_iPort_v04_2, __PLAYER_PAGE_TITLE$ );
   DECLARE_STRING_STRUCT( S2_iPort_v04_2, __PAGE_TITLE_BUF$ );
   DECLARE_STRING_STRUCT( S2_iPort_v04_2, __TITLE_PLAYLIST$ );
   DECLARE_STRING_STRUCT( S2_iPort_v04_2, __TITLE_ARTIST$ );
   DECLARE_STRING_STRUCT( S2_iPort_v04_2, __TITLE_ALBUM$ );
   DECLARE_STRING_STRUCT( S2_iPort_v04_2, __TITLE_GENRE$ );
   DECLARE_STRING_STRUCT( S2_iPort_v04_2, __TITLE_COMPOSER$ );
   DECLARE_STRING_STRUCT( S2_iPort_v04_2, __TITLE_PODCAST$ );
   DECLARE_STRING_STRUCT( S2_iPort_v04_2, __TITLE_AUDIOBOOK$ );
   DECLARE_STRING_STRUCT( S2_iPort_v04_2, __OUT_LINE1_BUF$ );
   DECLARE_STRING_STRUCT( S2_iPort_v04_2, __OUT_LINE2_BUF$ );
   DECLARE_STRING_STRUCT( S2_iPort_v04_2, __OUT_LINE3_BUF$ );
   DECLARE_STRING_STRUCT( S2_iPort_v04_2, __OUT_LINE4_BUF$ );
   DECLARE_STRING_STRUCT( S2_iPort_v04_2, __OUT_LINE5_BUF$ );
   DECLARE_STRING_STRUCT( S2_iPort_v04_2, __OUT_LINE6_BUF$ );
   DECLARE_STRING_STRUCT( S2_iPort_v04_2, __OUT_LINE7_BUF$ );
   DECLARE_STRING_STRUCT( S2_iPort_v04_2, __OUT_LINE8_BUF$ );
   DECLARE_STRING_STRUCT( S2_iPort_v04_2, __OUT_LINE9_BUF$ );
   DECLARE_STRING_STRUCT( S2_iPort_v04_2, __OUT_LINE10_BUF$ );
   DECLARE_STRING_STRUCT( S2_iPort_v04_2, __OUT_LINE11_BUF$ );
   DECLARE_STRING_STRUCT( S2_iPort_v04_2, __OUT_LINE12_BUF$ );
   DECLARE_STRING_STRUCT( S2_iPort_v04_2, __OUT_LINE13_BUF$ );
   DECLARE_STRING_STRUCT( S2_iPort_v04_2, __OUT_LINE14_BUF$ );
   DECLARE_STRING_STRUCT( S2_iPort_v04_2, __OUT_LINE15_BUF$ );
   DECLARE_STRING_STRUCT( S2_iPort_v04_2, __OUT_LINE16_BUF$ );
   DECLARE_STRING_STRUCT( S2_iPort_v04_2, __OUT_LINE17_BUF$ );
   DECLARE_STRING_STRUCT( S2_iPort_v04_2, __OUT_LINE18_BUF$ );
   DECLARE_STRING_STRUCT( S2_iPort_v04_2, __OUT_LINE19_BUF$ );
   DECLARE_STRING_STRUCT( S2_iPort_v04_2, __OUT_LINE20_BUF$ );
   DECLARE_STRING_STRUCT( S2_iPort_v04_2, __OUT_LINE21_BUF$ );
   DECLARE_STRING_STRUCT( S2_iPort_v04_2, __OUT_LINE22_BUF$ );
   DECLARE_STRING_STRUCT( S2_iPort_v04_2, __OUT_LINE23_BUF$ );
   DECLARE_STRING_STRUCT( S2_iPort_v04_2, __OUT_LINE24_BUF$ );
   DECLARE_STRING_STRUCT( S2_iPort_v04_2, __OUT_LINE25_BUF$ );
   DECLARE_STRING_STRUCT( S2_iPort_v04_2, __OUT_LINE26_BUF$ );
   DECLARE_STRING_STRUCT( S2_iPort_v04_2, __OUT_LINE27_BUF$ );
   DECLARE_STRING_STRUCT( S2_iPort_v04_2, __OUT_LINE28_BUF$ );
   DECLARE_STRING_STRUCT( S2_iPort_v04_2, __OUT_LINE29_BUF$ );
   DECLARE_STRING_STRUCT( S2_iPort_v04_2, __OUT_LINE30_BUF$ );
   DECLARE_STRING_STRUCT( S2_iPort_v04_2, __OUT_LINE31_BUF$ );
   DECLARE_STRING_STRUCT( S2_iPort_v04_2, __OUT_LINE32_BUF$ );
   DECLARE_STRING_STRUCT( S2_iPort_v04_2, __DATA_TO_PROCESS$ );
   DECLARE_STRING_STRUCT( S2_iPort_v04_2, __TEMP_LINE_OUT$ );
   DECLARE_STRING_STRUCT( S2_iPort_v04_2, __TEMP_FIRMWARE_VER$ );
   DECLARE_STRING_STRUCT( S2_iPort_v04_2, __DATA_TO_PROCESS_TEMP$ );
   DECLARE_STRING_STRUCT( S2_iPort_v04_2, __DATA_IN$ );
};

START_NVRAM_VAR_STRUCT( S2_iPort_v04_2 )
{
};

DEFINE_WAITEVENT( S2_iPort_v04_2, PLAYER_WAIT );
DEFINE_WAITEVENT( S2_iPort_v04_2, PLAYER_WAIT_MAIN );
DEFINE_WAITEVENT( S2_iPort_v04_2, NEXT_WAIT );
DEFINE_WAITEVENT( S2_iPort_v04_2, PREV_WAIT );


#endif //__S2_IPORT_V04_2_H__

