#ifndef __S2_MARANTZ_AV7702_PROCESSOR_V1_0_H__
#define __S2_MARANTZ_AV7702_PROCESSOR_V1_0_H__




/*
* Constructor and Destructor
*/

/*
* DIGITAL_INPUT
*/
#define __S2_Marantz_AV7702_Processor_v1_0_AM_SELECTED_DIG_INPUT 0
#define __S2_Marantz_AV7702_Processor_v1_0_FM_SELECTED_DIG_INPUT 1
#define __S2_Marantz_AV7702_Processor_v1_0_CLEAR_DIG_INPUT 2

#define __S2_Marantz_AV7702_Processor_v1_0_HD_TUNER_KP_DIG_INPUT 3
#define __S2_Marantz_AV7702_Processor_v1_0_HD_TUNER_KP_ARRAY_LENGTH 12

/*
* ANALOG_INPUT
*/


#define __S2_Marantz_AV7702_Processor_v1_0_FROM_DEVICE_BUFFER_INPUT 0
#define __S2_Marantz_AV7702_Processor_v1_0_FROM_DEVICE_BUFFER_MAX_LEN 50000
CREATE_STRING_STRUCT( S2_Marantz_AV7702_Processor_v1_0, __FROM_DEVICE, __S2_Marantz_AV7702_Processor_v1_0_FROM_DEVICE_BUFFER_MAX_LEN );
#define __S2_Marantz_AV7702_Processor_v1_0_RESPONSE_NSE_BUFFER_INPUT 1
#define __S2_Marantz_AV7702_Processor_v1_0_RESPONSE_NSE_BUFFER_MAX_LEN 125
CREATE_STRING_STRUCT( S2_Marantz_AV7702_Processor_v1_0, __RESPONSE_NSE, __S2_Marantz_AV7702_Processor_v1_0_RESPONSE_NSE_BUFFER_MAX_LEN );


/*
* DIGITAL_OUTPUT
*/

#define __S2_Marantz_AV7702_Processor_v1_0_HIGHLIGHT_LINE_DIG_OUTPUT 0
#define __S2_Marantz_AV7702_Processor_v1_0_HIGHLIGHT_LINE_ARRAY_LENGTH 8

/*
* ANALOG_OUTPUT
*/
#define __S2_Marantz_AV7702_Processor_v1_0_MAIN_VOLUME_GAUGE_ANALOG_OUTPUT 1
#define __S2_Marantz_AV7702_Processor_v1_0_ZONE_2_VOLUME_GAUGE_ANALOG_OUTPUT 3
#define __S2_Marantz_AV7702_Processor_v1_0_ZONE_3_VOLUME_GAUGE_ANALOG_OUTPUT 5

#define __S2_Marantz_AV7702_Processor_v1_0_MAIN_VOLUME_TEXT_STRING_OUTPUT 0
#define __S2_Marantz_AV7702_Processor_v1_0_ZONE_2_VOLUME_TEXT_STRING_OUTPUT 2
#define __S2_Marantz_AV7702_Processor_v1_0_ZONE_3_VOLUME_TEXT_STRING_OUTPUT 4
#define __S2_Marantz_AV7702_Processor_v1_0_FRONT_LEFT_LEVEL_TEXT_STRING_OUTPUT 6
#define __S2_Marantz_AV7702_Processor_v1_0_FRONT_RIGHT_LEVEL_TEXT_STRING_OUTPUT 7
#define __S2_Marantz_AV7702_Processor_v1_0_CENTER_LEVEL_TEXT_STRING_OUTPUT 8
#define __S2_Marantz_AV7702_Processor_v1_0_SUBWOOFER_LEVEL_TEXT_STRING_OUTPUT 9
#define __S2_Marantz_AV7702_Processor_v1_0_SUBWOOFER_2_LEVEL_TEXT_STRING_OUTPUT 10
#define __S2_Marantz_AV7702_Processor_v1_0_SURROUND_LEFT_LEVEL_TEXT_STRING_OUTPUT 11
#define __S2_Marantz_AV7702_Processor_v1_0_SURROUND_RIGHT_LEVEL_TEXT_STRING_OUTPUT 12
#define __S2_Marantz_AV7702_Processor_v1_0_SURROUND_BACK_LEFT_LEVEL_TEXT_STRING_OUTPUT 13
#define __S2_Marantz_AV7702_Processor_v1_0_SURROUND_BACK_RIGHT_LEVEL_TEXT_STRING_OUTPUT 14
#define __S2_Marantz_AV7702_Processor_v1_0_SURROUND_BACK_LEVEL_TEXT_STRING_OUTPUT 15
#define __S2_Marantz_AV7702_Processor_v1_0_FRONT_HEIGHT_LEFT_LEVEL_TEXT_STRING_OUTPUT 16
#define __S2_Marantz_AV7702_Processor_v1_0_FRONT_HEIGHT_RIGHT_LEVEL_TEXT_STRING_OUTPUT 17
#define __S2_Marantz_AV7702_Processor_v1_0_FRONT_WIDE_LEFT_LEVEL_TEXT_STRING_OUTPUT 18
#define __S2_Marantz_AV7702_Processor_v1_0_FRONT_WIDE_RIGHT_LEVEL_TEXT_STRING_OUTPUT 19
#define __S2_Marantz_AV7702_Processor_v1_0_TUNER_FREQUENCY_STRING_OUTPUT 20
#define __S2_Marantz_AV7702_Processor_v1_0_TO_DEVICE_STRING_OUTPUT 21

#define __S2_Marantz_AV7702_Processor_v1_0_LINE_OUT_STRING_OUTPUT 22
#define __S2_Marantz_AV7702_Processor_v1_0_LINE_OUT_ARRAY_LENGTH 9
#define __S2_Marantz_AV7702_Processor_v1_0_NET_AUDIO_PRESET_NAME_TEXT_STRING_OUTPUT 31
#define __S2_Marantz_AV7702_Processor_v1_0_NET_AUDIO_PRESET_NAME_TEXT_ARRAY_LENGTH 40

/*
* Direct Socket Variables
*/




/*
* INTEGER_PARAMETER
*/
/*
* SIGNED_INTEGER_PARAMETER
*/
/*
* LONG_INTEGER_PARAMETER
*/
/*
* SIGNED_LONG_INTEGER_PARAMETER
*/
/*
* INTEGER_PARAMETER
*/
/*
* SIGNED_INTEGER_PARAMETER
*/
/*
* LONG_INTEGER_PARAMETER
*/
/*
* SIGNED_LONG_INTEGER_PARAMETER
*/
/*
* STRING_PARAMETER
*/


/*
* INTEGER
*/


/*
* LONG_INTEGER
*/


/*
* SIGNED_INTEGER
*/


/*
* SIGNED_LONG_INTEGER
*/


/*
* STRING
*/
#define __S2_Marantz_AV7702_Processor_v1_0_SHDTUNERNUMBER_STRING_MAX_LEN 4
CREATE_STRING_STRUCT( S2_Marantz_AV7702_Processor_v1_0, __SHDTUNERNUMBER, __S2_Marantz_AV7702_Processor_v1_0_SHDTUNERNUMBER_STRING_MAX_LEN );
#define __S2_Marantz_AV7702_Processor_v1_0_SHDTUNERCOMMAND_STRING_MAX_LEN 10
CREATE_STRING_STRUCT( S2_Marantz_AV7702_Processor_v1_0, __SHDTUNERCOMMAND, __S2_Marantz_AV7702_Processor_v1_0_SHDTUNERCOMMAND_STRING_MAX_LEN );
#define __S2_Marantz_AV7702_Processor_v1_0_SFROMDEVICE_STRING_MAX_LEN 5000
CREATE_STRING_STRUCT( S2_Marantz_AV7702_Processor_v1_0, __SFROMDEVICE, __S2_Marantz_AV7702_Processor_v1_0_SFROMDEVICE_STRING_MAX_LEN );
#define __S2_Marantz_AV7702_Processor_v1_0_SRESPONSE_STRING_MAX_LEN 125
CREATE_STRING_STRUCT( S2_Marantz_AV7702_Processor_v1_0, __SRESPONSE, __S2_Marantz_AV7702_Processor_v1_0_SRESPONSE_STRING_MAX_LEN );
#define __S2_Marantz_AV7702_Processor_v1_0_SDUMP_STRING_MAX_LEN 150
CREATE_STRING_STRUCT( S2_Marantz_AV7702_Processor_v1_0, __SDUMP, __S2_Marantz_AV7702_Processor_v1_0_SDUMP_STRING_MAX_LEN );
#define __S2_Marantz_AV7702_Processor_v1_0_SSELECTEDCHAR_STRING_MAX_LEN 1
CREATE_STRING_STRUCT( S2_Marantz_AV7702_Processor_v1_0, __SSELECTEDCHAR, __S2_Marantz_AV7702_Processor_v1_0_SSELECTEDCHAR_STRING_MAX_LEN );

/*
* STRUCTURE
*/

START_GLOBAL_VAR_STRUCT( S2_Marantz_AV7702_Processor_v1_0 )
{
   void* InstancePtr;
   struct GenericOutputString_s sGenericOutStr;
   unsigned short LastModifiedArrayIndex;

   DECLARE_IO_ARRAY( __HD_TUNER_KP );
   DECLARE_IO_ARRAY( __HIGHLIGHT_LINE );
   DECLARE_IO_ARRAY( __LINE_OUT );
   DECLARE_IO_ARRAY( __NET_AUDIO_PRESET_NAME_TEXT );
   unsigned short __IPROCESSFROMDEVICE;
   unsigned short __IVALUE;
   unsigned short __IMVMAX;
   unsigned short __ISTATIONVALUE;
   unsigned short __ISEMAPHORE;
   unsigned short __ISTRINGNUMBER;
   DECLARE_STRING_STRUCT( S2_Marantz_AV7702_Processor_v1_0, __SHDTUNERNUMBER );
   DECLARE_STRING_STRUCT( S2_Marantz_AV7702_Processor_v1_0, __SHDTUNERCOMMAND );
   DECLARE_STRING_STRUCT( S2_Marantz_AV7702_Processor_v1_0, __SFROMDEVICE );
   DECLARE_STRING_STRUCT( S2_Marantz_AV7702_Processor_v1_0, __SRESPONSE );
   DECLARE_STRING_STRUCT( S2_Marantz_AV7702_Processor_v1_0, __SDUMP );
   DECLARE_STRING_STRUCT( S2_Marantz_AV7702_Processor_v1_0, __SSELECTEDCHAR );
   DECLARE_STRING_STRUCT( S2_Marantz_AV7702_Processor_v1_0, __FROM_DEVICE );
   DECLARE_STRING_STRUCT( S2_Marantz_AV7702_Processor_v1_0, __RESPONSE_NSE );
};

START_NVRAM_VAR_STRUCT( S2_Marantz_AV7702_Processor_v1_0 )
{
};



#endif //__S2_MARANTZ_AV7702_PROCESSOR_V1_0_H__

